repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict

  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  # JavaScript formatting and linting
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: eslint
        language: node
        files: \.(js|jsx|ts|tsx)$
        additional_dependencies:
          - eslint@^9.29.0
          - eslint-config-prettier@^10.1.5
      - id: prettier
        name: prettier
        entry: prettier
        args: ["--check"]
        language: node
        files: \.(js|jsx|ts|tsx|json|css|md)$
        additional_dependencies:
          - prettier@^3.6.0

  # Project metadata consistency check
  - repo: local
    hooks:
      - id: check-project-consistency
        name: Check project metadata consistency
        entry: python scripts/check_project_consistency.py
        language: python
        files: '(pyproject\.toml|package\.json)$'
        pass_filenames: false
        additional_dependencies:
          - tomlkit==0.12.0

  # Commit message formatting
  - repo: local
    hooks:
      - id: capitalize-commit-msg
        name: Capitalize commit message
        entry: bash -c 'first_char=$(head -c 1 "$1"); rest=$(tail -c +2 "$1"); echo "${first_char^}${rest}" > "$1"' --
        language: system
        stages: [commit-msg]
        pass_filenames: true
